version: "3.8"

services:
  db:
    image: mysql

    environment:
      - NAME=django_db
      - USER=root
      - MYSQL_ROOT_PASSWORD=root
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
        - NAME=django_db
        - USER=root
        - MYSQL_ROOT_PASSWORD=root
    depends_on:
      - db